bf: windows: simplify further.
	* buildfarm/common: Define variables here.
	* buildfarm/make-installer: use these variables.
	Remove useless option handling.
	* buildfarm/package: Don't pass them.

diff --git a/buildfarm/common b/buildfarm/common
--- a/buildfarm/common
+++ b/buildfarm/common
@@ -89,8 +89,6 @@ xcp ()
   fatal "cannot: cp $*"
 }
 
-
-
 # xmv ARG...
 # ----------
 # Wrapper around "mv" that tries to do things three times, then fail.
@@ -107,6 +105,8 @@ xmv ()
   done
   fatal "cannot: mv $*"
 }
+
+
 
 ## ----------- ##
 ## Variables.  ##
@@ -198,6 +198,7 @@ esac
 ## --------------------- ##
 
 stderr "$BUILDFARM_HOSTNAME: $BUILDFARM_PROJECT-$BUILDFARM_NAME-$BUILDFARM_MODE"
+stderr "Version: SHA1"
 
 # We really want ps to work.
 #
@@ -214,18 +215,37 @@ stderr "$BUILDFARM_HOSTNAME: $BUILDFARM_PROJECT-$BUILDFARM_NAME-$BUILDFARM_MODE"
 #
 # Beware that on OS X, if "ps" sees no process, it fails.  "ps x"
 # should help.
-if ! ps x; then
+if ! ps x >/dev/null; then
   fatal "ps does not work, is procfs properly mounted?"
 fi
 
 set -x
 
 # We need share.
-sharedir=$HOME/share
 readme=$sharedir/README-share.txt
 if test ! -f $readme; then
   fatal "share/ does not seem to be mounted properly: there is no $readme"
 fi
+
+# tools.
+toolsdir=$sharedir/tools
+# We need vcxx-2005, not vcxx2005.
+vcxx=$(echo "$BUILDFARM_COMPILER" | perl -pe 's/(vcxx)(\d+)/$1-$2/')
+# vcredist has name with vcxx-2005, not vcxx2005.
+vcredist=$toolsdir/vcredist/vcredist_x86-$vcxx.exe
+gostai_console="$toolsdir/gostai-console/gostai-console-2.6-win32.exe"
+gostai_editor="$toolsdir/gostai-editor/gostai-editor-2.5-win32.exe"
+for i in vcredist gostai_console gostai_editor
+do
+  eval "file=\$$i"
+  test -r "$file" ||
+    fatal "cannot read $i: $val"
+  test -f "$file" ||
+    fatal "not a file $i: $val"
+  test -s "$file" ||
+    fatal "empty file $i: $val"
+done
+
 
 # colordiff sometimes does not tell different files apart (e.g., on
 # Debian Etch).
