Comment changes.

diff --git a/scripts/publish-latest b/scripts/publish-latest
--- a/scripts/publish-latest
+++ b/scripts/publish-latest
@@ -1,5 +1,8 @@
 #! /bin/sh -e
 
+# stderr LINE...
+# --------------
+# Issue the lines on stderr.
 stderr ()
 {
   local i
@@ -9,6 +12,9 @@ stderr ()
   done
 }
 
+# error STATUS LINE...
+# ---------------------
+# Issue the lines as error, and exit STATUS.
 error ()
 {
   local sta=$1
@@ -17,11 +23,17 @@ error ()
   exit $sta
 }
 
+# fatal LINE...
+# -------------
+# Issue the lines as error, and exit 1.
 fatal ()
 {
   error 1 "$@"
 }
 
+# usage
+# -----
+# Report usage and exit successfully.
 usage ()
 {
   cat <<EOF
@@ -44,6 +56,10 @@ Options:
 EOF
   exit 0
 }
+
+# getargs
+# -------
+# Process the command line arguments.
 getargs ()
 {
   while test $# -ne 0;
@@ -58,6 +74,8 @@ getargs ()
   done
 }
 
+# scp_user LOC
+# ------------
 # From an scp-like location, return the user.
 # foo@bar.baz.com:my/path -> foo
 scp_user ()
@@ -65,6 +83,8 @@ scp_user ()
   echo "$1" | sed -e 's/@.*//'
 }
 
+# scp_host LOC
+# ------------
 # From an scp-like location, return the host name.
 # foo@bar.baz.com:my/path -> bar.baz.com
 scp_host ()
@@ -72,6 +92,8 @@ scp_host ()
   echo "$1" | sed -e 's/.*@//;s/:.*//'
 }
 
+# scp_dir LOC
+# -----------
 # From a scp-like location, return the path.
 # foo@bar.baz.com:my/path -> my/path
 scp_dir ()
@@ -79,6 +101,8 @@ scp_dir ()
   echo "$1" | sed -e 's/.*://'
 }
 
+# scp_point LOC
+# --------------
 # From a scp-like location, return the connection-point.
 # foo@bar.baz.com:my/path -> foo@bar.baz.com
 scp_point ()
@@ -87,6 +111,10 @@ scp_point ()
 }
 
 
+
+## ------ ##
+## Main.  ##
+## ------ ##
 
 # The (scp-like) directory that contains the tarballs.
 from=build@bf-1:share/built/kernel-2.0/archives
