Accept that urbi-server is not installed.
	* tests/Makefile.am (URBISERVER): Set to false when not available.
	* tests/liburbi-check: Adjust.

git-svn-id: file:///srv/svn/liburbi-cpp/trunk@579 b8db33d8-8104-0410-b827-8403f563b8eb

diff --git a/sdk-remote/tests/liburbi-check b/sdk-remote/tests/liburbi-check
--- a/sdk-remote/tests/liburbi-check
+++ b/sdk-remote/tests/liburbi-check
@@ -107,25 +107,30 @@ my_sleep ()
 
 find_urbiserver ()
 {
-  # If URBISERVER is not defined, try to find one.
-  if test -z "$URBISERVER"; then
-    # If we are in $top_builddir/tests/TEST.dir, then look in $top_builddir/src.
-    for i in $top_builddir/src .
-    do
-      if test -f "$i/urbi-server"; then
-	URBISERVER=$i/urbi-server
-	break
-      fi
-    done
+  case $URBISERVER in
+    false) #  If not installed, skip.
+       exit 77
+       ;;
+    '')
+       # If URBISERVER is not defined, try to find one.  If we are in
+       # $top_builddir/tests/TEST.dir, then look in $top_builddir/src.
+       for i in $top_builddir/src .
+       do
+         if test -f "$i/urbi-server"; then
+   	   URBISERVER=$i/urbi-server
+   	   break
+         fi
+       done
+   
+       if test -z "$URBISERVER"; then
+         fatal "cannot find urbi-server, please define URBISERVER"
+       fi
+       ;;
+  esac
 
-    if test -z "$URBISERVER"; then
-      fatal "cannot find urbi-server, please define URBISERVER"
-    fi
-  fi
-
-  # Check for URBISERVER
+  # Check for URBISERVER. 
   if test ! -f "$URBISERVER"; then
-    fatal "cannot find urbi-server, please check URBISERVER: $URBISERVER"
+    fatal "cannot find urbi-server, please check \$URBISERVER: $URBISERVER"
   fi
 
   # Check its version.
