Fix the finding of urbi-server.
	* tests/Makefile.am (URBISERVER): Rename as...
	(URBI_SERVER): This.
	No longer compute it here.
	* tests/liburbi-check (absolute, find_prog, $path_sep): New,
	inspired by their counterparts in texi2dvi.
	(find_urbiserver, URBISERVER): Rename as...
	(find_urbi_server, URBI)SERVER): these.
	Use these recently introduced functions.
	No longer echo the result, just set URBI_SERVER.
	Use absolute.

git-svn-id: file:///srv/svn/liburbi-cpp/trunk@580 b8db33d8-8104-0410-b827-8403f563b8eb

diff --git a/sdk-remote/tests/liburbi-check b/sdk-remote/tests/liburbi-check
--- a/sdk-remote/tests/liburbi-check
+++ b/sdk-remote/tests/liburbi-check
@@ -52,6 +52,75 @@ fatal ()
 }
 
 
+# Systems which define $COMSPEC or $ComSpec use semicolons to separate
+# directories in TEXINPUTS -- except for Cygwin, where COMSPEC might be
+# inherited, but : is used.
+if test -n "$COMSPEC$ComSpec" && uname | grep -iv cygwin >/dev/null; then
+  path_sep=";"
+else
+  path_sep=":"
+fi
+
+# find_prog PROG PATH
+# -------------------
+# Return full path to PROG in PATH (path_sep separated), nothing if not found.
+find_prog ()
+{
+  local prog=$1
+  local path=$2
+  local save_IFS=$IFS
+  IFS=$path_sep  # break path components at the path separator
+  for dir in $path
+  do
+    IFS=$save_IFS
+    # The basic test for an executable is `test -f $f && test -x $f'.
+    # (`test -x' is not enough, because it can also be true for directories.)
+    # We have to try this both for $1 and $1.exe.
+    #
+    # Note: On Cygwin and DJGPP, `test -x' also looks for .exe.  On Cygwin,
+    # also `test -f' has this enhancement, but not on DJGPP.  (Both are
+    # design decisions, so there is little chance to make them consistent.)
+    # Thusly, it seems to be difficult to make use of these enhancements.
+    #
+    if  { test -f "$dir/$1"	&& test -x "$dir/$1"; } ||
+	{ test -f "$dir/$1.exe"	&& test -x "$dir/$1.exe"; }; then
+      echo "$dir/$1"
+      break
+    fi
+  done
+}
+
+# absolute NAME -> ABS-NAME
+# -------------------------
+# Return an absolute path to NAME.
+absolute ()
+{
+  local res
+  case $1 in
+   [\\/]* | ?:[\\/]*)
+      # Absolute paths don't need to be expanded.
+      res=$1
+      ;;
+   *) local dir=$(pwd)/$(dirname "$1")
+      if test -d "$dir"; then
+	res=$(cd "$dir" 2>/dev/null && pwd)/$(basename "$1")
+      else
+	fatal "not a directory: $dir"
+      fi
+      ;;
+  esac
+
+  # On Windows, we must make sure we have a Windows-like UNIX-friendly path (of
+  # the form C:/cygwin/path/to/somewhere instead of /path/to/somewhere, notice
+  # the use of forward slashes in the Windows path.  Windows *does* understand
+  # paths with forward slashes).
+  case $(uname -s) in
+    CYGWIN*) res=$(cygpath --mixed "$res")
+  esac
+  echo "$res"
+}
+
+
 # run TITLE COMMAND...
 # --------------------
 # Run the COMMAND... (which may use its stdin) and output detailed
@@ -104,40 +173,43 @@ my_sleep ()
   fi
 }
 
-
-find_urbiserver ()
+# find_urbi_server
+# ----------------
+# Set URBI_SERVER to the location of urbi-server.
+find_urbi_server ()
 {
-  case $URBISERVER in
-    false) #  If not installed, skip.
-       exit 77
-       ;;
+  case $URBI_SERVER in
     '')
-       # If URBISERVER is not defined, try to find one.  If we are in
+       # If URBI_SERVER is not defined, try to find one.  If we are in
        # $top_builddir/tests/TEST.dir, then look in $top_builddir/src.
-       for i in $top_builddir/src .
-       do
-         if test -f "$i/urbi-server"; then
-   	   URBISERVER=$i/urbi-server
-   	   break
-         fi
-       done
-   
-       if test -z "$URBISERVER"; then
-         fatal "cannot find urbi-server, please define URBISERVER"
-       fi
+       URBI_SERVER=$(find_prog "urbi-server" "$top_builddir/src${path_sep}.")
+       ;;
+
+    *[\\/]* ) # A path, relative or absolute.  Make it absolute.
+       URBI_SERVER=$(absolute "$URBI_SERVER")
+       ;;
+
+    *) # A simple name, most certainly urbi-server.
+       # Find it in the PATH.
+       URBI_SERVER=$(find_prog "urbi-server" "$PATH")
+       # If we can't find it, then ucore-pc was probably not installed.
+       # Skip.
+       exit 77
        ;;
   esac
 
-  # Check for URBISERVER. 
-  if test ! -f "$URBISERVER"; then
-    fatal "cannot find urbi-server, please check \$URBISERVER: $URBISERVER"
+  if test -z "$URBI_SERVER"; then
+    fatal "cannot find urbi-server, please define URBI_SERVER"
+  fi
+
+  if test ! -f "$URBI_SERVER"; then
+    fatal "cannot find urbi-server, please check \$URBI_SERVER: $URBI_SERVER"
   fi
 
   # Check its version.
-  if ! run "Server version" "$URBISERVER" --version; then
-    fatal "cannot run $URBISERVER --version"
+  if ! run "Server version" "$URBI_SERVER" --version; then
+    fatal "cannot run $URBI_SERVER --version"
   fi
-  echo "$URBISERVER"
 }
 
 
@@ -321,12 +393,7 @@ find_srcdir ()
   fi
 
   # We may change directory.
-  case "$srcdir" in
-    [\\/]* | ?:[\\/]* )  # Absolute name.
-	;;
-    *) # Relative name.
-	srcdir=$(cd "$srcdir" && pwd);;
-  esac
+  srcdir=$(absolute "$srcdir")
 
   # Check that srcdir is valid.
   test -f "$srcdir/tests.hh" ||
@@ -351,6 +418,11 @@ me=$medir/$(basename "$chk" ".cc")
 meraw=$(basename $me)    # MERAW!
 # Guess srcdir if not defined.
 srcdir=$(find_srcdir)
+# $URBI_SERVER
+find_urbi_server
+
+# Help debugging
+set | pre "$me variables" >&3
 
 # Move to a private test directory.
 rm -rf $me.dir
@@ -364,14 +436,10 @@ sed -n -e 's@//= @@p' $chk.cc >output.exp
 touch error.exp
 echo 0 >status.exp
 
-#urbi-server check
-URBISERVER=$(find_urbiserver)
-
-
 #start it
 valgrind=$(instrument "server.val")
-echo $valgrind $URBISERVER -p 0 -w server.port $period >server.cmd
-$valgrind $URBISERVER -p 0 -w server.port $period >server.out 2>server.err &
+echo $valgrind $URBI_SERVER -p 0 -w server.port $period >server.cmd
+$valgrind $URBI_SERVER -p 0 -w server.port $period >server.out 2>server.err &
 register_child server
 
 my_sleep 2
